package br.ufscar.pescd.model;

public enum StatusPlano {
    PENDENTE,
    ENVIADO,
    APROVADO,
    REJEITADO,
    DOCUMENTACAO_ENVIADA,
    RELATORIO_ENVIADO,
    RELATORIO_APROVADO_SUPERVISOR,
    CONCLUIDO_PELO_RESPONSAVEL
}